keys:
  - &madeddie age13jkfzky97zmm4n738k3wy8leguhz6xy6xas9r4etnx2esyafadvqat4qve
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|lua)$
    key_groups:
    - age:
      - *madeddie

