[default]
output = ENC[AES256_GCM,data:vUHGdw==,iv:6liVOGH0g5HvVDjvBSSrKA2vA76TWEMWXJ9FCzBkBe0=,tag:lTpmjw0tbcOSB16V7SZUoQ==,type:str]
region = ENC[AES256_GCM,data:+ruxZdWFLIKs,iv:JNC5+++Tzyo108wMculJshtSsPQjCupRMDTmtx5Wymg=,tag:rElt3s48Rh8UdPhOmZoZnw==,type:str]

[profile madtech]
output = ENC[AES256_GCM,data:DBK5wA==,iv:z1UspA9QQUZq2shw34UshQnSDnS4szpTJpu/h7aRmeE=,tag:7l6PmFWlD1MVP4gF2WCJeQ==,type:str]
region = ENC[AES256_GCM,data:kFfzRsSlmq7N,iv:zrnMzw6tUEtIwMbLKBcmvmvWkaEUaIC3rgSgjTATzhk=,tag:rxlfbM+pRgmDJ13mI9fHOQ==,type:str]

[profile madtech_idrivee2]
region       = ENC[AES256_GCM,data:RlOA+X+NKQ9J,iv:Z1wFicUDRIi+vewdGHYVW/kgSsj4rj+a9t6B++T6Thw=,tag:iGiRZqULSBWg2fTKlzpJyw==,type:str]
endpoint_url = ENC[AES256_GCM,data:zkR6wT9jyR7GhgavfW8JjLLor/MpK3LA1zsWBOUAYG/q,iv:A4i60wxnTLDpCHz6JYB0tVNg5KvbBey7wzyWSQlei+A=,tag:3BjAjwYn/UPjd2H29YIjlg==,type:str]

[sso-session edwinh_macbook]
sso_start_url           = ENC[AES256_GCM,data:Mjn9BPFoVzK5XiAO58nXbs7wcSvpzddBYuBzKDz1rph6IfVYUw==,iv:/8RyApQxTe+XFATvRBYeeUe6oquQAi/oPvJ0m1u3VnA=,tag:8yd0N/VxmbXiv8YiAmOTRQ==,type:str]
sso_region              = ENC[AES256_GCM,data:E/5ixSaFZiNm,iv:D49FI0kf51mvZCWB4sasyIjE6FFtnkX5vKnQtUx+XM4=,tag:cyU+HDxniMPqyHXLY9YhyA==,type:str]
sso_registration_scopes = ENC[AES256_GCM,data:sw66Zk4ouf0OIj+NA9x6KdZB,iv:a4Qf3kOnTmlmBciEhAEGb0raovvroldOn8UN+0BkYrM=,tag:vCpMeJ7qz4OqZzG+Ce0cYw==,type:str]

[profile porter_edwin]
sso_session    = ENC[AES256_GCM,data:oxmWJ4H/5sBmIBNdMrM=,iv:LWVDKv4w8uReiQl6z2vNRfoPiUC6B20nvjhCJKS5w/c=,tag:q4IEEU8LEAXw78UC7YSFFg==,type:str]
sso_account_id = ENC[AES256_GCM,data:iNVwmvuh1sNs1IaV,iv:lPPOua8zaC63dvax6dy9vW4KpZUvUMRJYWo/W3Vbkew=,tag:kSvJeV5fUvzqFcpUdEK2DA==,type:str]
sso_role_name  = ENC[AES256_GCM,data:iL7eVi775N9BK4Ei1DbNCphs1U8=,iv:Cw9kj3pQshVAUTe8jjyDpHKN0H6GB1f7EoHk2gUVRnM=,tag:FhOeKIOUSMqC+Ag5jOktGQ==,type:str]
region         = ENC[AES256_GCM,data:mmKd+M5RjUQD,iv:76Uw6aVf08/uv1O6pdOPsCXMUIx04fcwIx2LN5Kcmjw=,tag:Pk5sXIoZUX/fW5n/7aR95w==,type:str]
output         = ENC[AES256_GCM,data:SXUa7A==,iv:MGeHRVfyNKdkBhwyjMIkSwUav5aJhIi2EOpTgwfn1Bc=,tag:5n+jkvxPD3Sv0pfZ37Dqjg==,type:str]

[profile porter_internal_tooling]
sso_session    = ENC[AES256_GCM,data:N9w+S/V7jzNMU0sBEgw=,iv:KdUfC6Esv8abuR7Xb/EMOgXbH+dYjpL+qa1WmwiBs+8=,tag:IZVsyO3B44Z2u96+Fd94bw==,type:str]
sso_account_id = ENC[AES256_GCM,data:Bp/4TniiP8asgvRD,iv:XS7M3O9Gxx8yGOtLpcOUg+/KRDgkZV94nQtfvcR38/4=,tag:WLosf3Y/kofAHyXn54pmKQ==,type:str]
sso_role_name  = ENC[AES256_GCM,data:D1WsOsMCJpdy+pdv8cw1iay2Gllo6bDz,iv:/tA8WOybk4wXPGAw4Y+LCu0B/CBvjGhgm4xUxcwHLko=,tag:MaYJCzjOCvpXbjpukSw2bg==,type:str]
region         = ENC[AES256_GCM,data:2aIIRsJXay+k,iv:e2lp9ERQgZcCQXwRuyE7itpsUVsiWNxGeQmHcHDpAL4=,tag:mUh2iTFOJIVVdYxahN5gvg==,type:str]
output         = ENC[AES256_GCM,data:SZd9DQ==,iv:v6vUTRVvyOMzj2BMmnWdGNtchDw3cb06ClJ6xOEAdo0=,tag:jTJNYYcyj4sTUaKzO6Ep1A==,type:str]

[profile porter_audit]
sso_session    = ENC[AES256_GCM,data:JYIJqAqE83gWgzOKzkY=,iv:TouQZJtbcN5u1DZICVY7kqDSAv29I66Z+i+g8o5tuQc=,tag:gtzdoWtcQaTjHWlUrJXv9g==,type:str]
sso_account_id = ENC[AES256_GCM,data:/BJiyZzM4laVmv88,iv:CduwvsKEbIs2zKGsXwsfIOK61ufnEmV60bMtwZMA+CA=,tag:kbDXl6YVaGUKd4kDFsvEqg==,type:str]
sso_role_name  = ENC[AES256_GCM,data:nxUehwz/IbLKeGbpm2Zq,iv:h6q/GdF7BbeRpZetHzTbcH64lLLwIrgz/rGBu72fZdo=,tag:0PGqzym5rb3i4+PxPYzIKw==,type:str]
region         = ENC[AES256_GCM,data:XgN6xtEP+s5R,iv:qxuBQfPdSLFdYcZozJw9zbGCP3TTpXTLnrrDtxMF6/E=,tag:HaGMfNcXy9XZNoMzp4HwhQ==,type:str]
output         = ENC[AES256_GCM,data:kj/fPA==,iv:fAupBgM+TatLaZCcdo+xplN9Wchoajjtd4gjKRP8EgM=,tag:8SE0iUowqSoHJn963Y4IxQ==,type:str]

; ENC[AES256_GCM,data:iggUzt15og7JmRko9wjXlWNb97WSMnGLYQmp9wft4kR5hZAbibsqqZpvRmdkZWQXVzH4rE8OVX68NYc7/iUXOTS19i2AP5R2excM5xkraUIHmt6Ot22bSlQlJ/xWCnLSMQV/vXg4oUrG3JK35J7T/ZLQMAFu4oqdsbxhuDpxGmj2tekN1oyBaOcq8KPLGDGv5paD/kudetFD+pJdA5Tdv7TXpSkszPcTmvA+mcBJGb6whTpQtgKxmaLby0R+BvWFCUufCNltB1jynilK5TU2pQ7Z78rkzD0ghb10RAZhWvB2dHzGtgQFkH4A/S5fP3VPuF+AYSABUWKkc5moAusKQjsYB9sJnS0nG5NbK8IXb0n3KbN/bmn8Dbtoxmp8u6L5/yUt9sMYujd7kP6ac+wA5JIXA7a8VqbDjV1AquXuodLlCESQBCRyY91ISsURnSDpTocs+doG/bWAAFPA2tKshjBDosBUIlFj4NAFA6iac7NYwPgK/jrpbcR15NX2vyMe6iC9AUwTfOT2MUgf4fcNFOhe9j1FLNN6OIyk3QiTNiqfIapfb2z8qNU2Rgsrig/Ebk5bLedAMINyOyG5zwGikBLnalVVw+ZrfKaRV2Thq0NFzU8jwgBAuRY26Z3jBUjraUo99DNR2CdkFI/lL5cisP/yQjbPiZ43em50PAklrAo6rFcqp5vFUdeyOi5rOTOIrLycLUE0mWAC7c+Ya/xRoFb1wEc3oVEOENWPBiNvWD359VdhJRJabInk8r19kh5kyRFGd+ydbojUC4E8vSpew5NcKz8WQhMb5MqaRBkXOEZg7HADvETrWlg3KksLvvZpxNJdpBOi6g==,iv:gU5/zCSBJC6AJL4PLGIai9l0BXXQe6JO3nmDzr94Nxk=,tag:S6D86G0dlk3U4g6BfO+QrQ==,type:comment]
[profile porter_bastion]
sso_session    = ENC[AES256_GCM,data:6sPHaVkclWha1wlttHs=,iv:oHloWu7sfEip3hSCvLcZiYcwgci5vFuKOt3S+ps+yhU=,tag:LDxoiWTUbwRPvr4nXVvLVA==,type:str]
sso_account_id = ENC[AES256_GCM,data:eABB5evlK0pwQRSY,iv:U4VXS8z/0QL0jvw7dL6RYtDOu6InxX65NDzEkU5ZqY4=,tag:IDGbNzrCZE6b8qy0IHo6WA==,type:str]
sso_role_name  = ENC[AES256_GCM,data:klX+qG4m4qwhFAmnYhCDRahTOwVOa8es,iv:N25BWLclHk5SjnHugm7quL5cZkDFTO2v5wqTCuHnCSA=,tag:gG9/jTBvpaKmfzuD5u2qbg==,type:str]
region         = ENC[AES256_GCM,data:RhximLVOAN3W,iv:AHotO0RjPcXRS+hnijv8k7Mh8tLimO2VgfpXgEFToTE=,tag:MbU03QIkw9it4zKJH39y3Q==,type:str]
output         = ENC[AES256_GCM,data:4OXkZg==,iv:j73mVdO25aXPMzB3ZPC8ofMXVP/Un49gd9pMtF+bHN0=,tag:CT/yvmARKAzoXCbpUJovKw==,type:str]

[sops]
lastmodified               = 2026-05-04T19:29:36Z
mac                        = ENC[AES256_GCM,data:nneDB1zjyZ4EOpjv5qLNxJr+rsdiL94n1oxw3kr//XTLB9R74UyZv9g5xV1E1kwAkXBNPWf4zs+t/odU+VHC/AkCkB33hJBQnk2z7RNjiL/8qkQHvo/Q0GPoSGQl9aB5OaW3XjdNr/fig98T+Rv1TR4q/KeuNa6XJ/wHn5bDFmw=,iv:wCEStPaItvHjZgRAS6TWT5EyfL0mCoyZTai/zuncH0s=,tag:/KWruSIrCdHMOwh4D6Vkig==,type:str]
unencrypted_suffix         = _unencrypted
version                    = 3.12.2
age__list_0__map_enc       = -----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpU0JoTXk1ODE1dFhaVEsx\nL1VMTEtMNzc5aVViRFJORXpJMHV0aWYvR0VJClM4SUpPT2FIaG9JUnlBWnI0NWtX\nbDV6Qzl5dFo4NVpoZ2JCaTc5VE5iUDQKLS0tIG9DWDlEeU1oV0pGSVh5cGdSU3NY\nMDdITCswZUNXQiszZkNtU0Y4Qld1NGsKbknXdZmHp43YSKshrKfDO+FqqkUnSRr+\nY2JmDXsFOIvo9TNeMjkRLCYntBYna9n1b1IJ2i+TfEfS1aOAT7SynQ==\n-----END AGE ENCRYPTED FILE-----\n
age__list_0__map_recipient = age13jkfzky97zmm4n738k3wy8leguhz6xy6xas9r4etnx2esyafadvqat4qve
